# frozen_string_literal: true
source "https://rubygems.org"

gem "sinatra-activerecord"
gem "sqlite3"
gem "pry"
gem "require_all"
gem 'artii', '~> 2.1', '>= 2.1.2'
gem 'tty-spinner'
gem 'paint'
gem 'tty-prompt'
gem 'tty-logger'
